version: 2.1

# Define reusable executors for jobs that need to run in the same Docker containers
executors:
  docker:
    - image: cimg/postgres:16.7
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
        network_mode: bridge
    - image: cimg/ruby:3.0.5-node
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PSQL_PAGER: ''
          PAGER: cat # prevent psql commands using less
        network_mode: bridge
# Define reusable commands for steps
commands:
  wait_for_postgres:
    steps:
      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
  setup_artifacts_and_tests:
    steps:
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
  configure_bundler:
    steps:
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
  install_dependencies:
    steps:
      - run: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - run:
          name: Install gem dependencies
          command: sudo apt update && sudo apt install -y poppler-utils imagemagick libmagickcore-dev libmagickwand-dev pkg-config libgeos-dev libgeos++-dev libproj-dev || true
  bundle_lifetales:
    steps:
      - run:
          name: Bundle lifetalesV2-server
          command: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3'
  create_database_config:
    steps:
      - run: |-
          mkdir -p config && echo 'test:
            database: circle_test
            adapter: postgresql
            encoding: unicode
            pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
            username: ubuntu
            host: localhost
          ' > config/database.yml
  install_postgresql_client:
    steps:
      - run: sudo apt-get --allow-releaseinfo-change update
      - run: sudo apt install -y libvips postgresql-client poppler-utils || true
  run_migrations:
    steps:
      - run:
          name: Run migrations
          command: MAILERLITE_API_TOKEN=mailerlite-api-token RAILS_ENV=test bundle exec rails db:drop db:create db:schema:load --trace
  run_tests:
    steps:
      - run:
          name: Run rspec tests
          command: MAILERLITE_API_TOKEN=mailerlite-api-token RAILS_ENV=test bundle exec rspec --format progress $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings --timings-type=classname)
  store_test_results_and_artifacts:
    steps:
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results

# Define the build job
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.5-node
        environment:
          PGHOST: localhost 
          PGUSER: root
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
      - image: cimg/postgres:16.7
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
    working_directory: ~/LifeTales/lifetalesV2-server
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 10m
      - setup_artifacts_and_tests
      - configure_bundler
      - install_dependencies
      - bundle_lifetales
      - create_database_config
      - install_postgresql_client
      - run_migrations
      - run_tests
      - store_test_results_and_artifacts

workflows:
  version: 2
  build:
    jobs:
      - build
