version: 2.1

jobs:
  build:
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test
    # Primary container image where all commands run
    docker:
      - image: cimg/ruby:3.0.5-node
        environment:
          #TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: ubuntu
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PSQL_PAGER: ''
          PAGER: cat # prevent psql commands using less

    # Service container image
      - image: cimg/postgres:16.7
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test

    steps:
      # Checkout the code as the first step.
      - checkout:
          path: /home/circleci/project
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - run: 
          name: install gem dependencies
          #command: sudo apt update && sudo apt install -y nodejs poppler-utils imagemagick libmagickcore-dev libmagickwand-dev pkg-config libgeos-dev libgeos++-dev libproj-dev || true
          command: sudo apt update && sudo apt install -y poppler-utils imagemagick libmagickcore-dev libmagickwand-dev pkg-config libgeos-dev libgeos++-dev libproj-dev || true
      - run:
          name: bundle lifetalesV2-server
          command: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3'
      - run: |-
          mkdir -p config && echo 'test:
            database: circle_test
            adapter: postgresql
            encoding: unicode
            pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
            username: ubuntu
            host: localhost
          ' > config/database.yml
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: |
          psql \
          -d postgresql://ubuntu@localhost/circle_test \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d postgresql://ubuntu@localhost/circle_test \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      - run:
          name: "Debug: Check if Gemfile exists"
          command: ls -la /home/circleci/project
